const studentList = [
  { id: 1, name: "กร" },
  { id: 2, name: "กนก" },
  { id: 3, name: "แก้ว" },
  { id: 4, name: "สมปอง" },
  { id: 5, name: "สมหมาย" },
  { id: 6, name: "สมาน" },
  { id: 7, name: "ยืนยง" },
  { id: 8, name: "เตชิต" },
  { id: 9, name: "ณรงค์" },
  { id: 10, name: "ปกรณ์" },
  { id: 11, name: "โสพิส" },
  { id: 12, name: "สุดา" },
  { id: 13, name: "สุนารี" },
  { id: 14, name: "สมศรี" },
  { id: 15, name: "กรกนก" },
  { id: 16, name: "นภาพร" },
  { id: 17, name: "พรนภา" },
  { id: 18, name: "พิรชา" },
  { id: 19, name: "วิชุดา" },
  { id: 20, name: "พงษ์เดช" },
  { id: 21, name: "สมศักดิ์" },
  { id: 22, name: "หิรัญ" },
  { id: 23, name: "ดวงกมล" },
  { id: 24, name: "ปฐม" },
  { id: 25, name: "ครรชิต" },
  { id: 26, name: "ปัทมา" },
  { id: 27, name: "ปัทมพร" },
  { id: 28, name: "ปาณิสรา" },
  { id: 29, name: "ชัยชิต" },
  { id: 30, name: "เดชฉกรร" },
  { id: 31, name: "พราว" },
  { id: 32, name: "แพรว" },
  { id: 33, name: "พานุพงษ์" },
  { id: 34, name: "พรพรรณ" },
  { id: 35, name: "ภาคภูมิ" },
  { id: 36, name: "จิตกร" },
  { id: 37, name: "สมชาย" },
];

export default studentList;
